# Generated by Django 3.2.4 on 2021-06-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criptos',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase_price', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('cantity', models.FloatField()),
                ('able', models.IntegerField()),
                ('date_purchase', models.DateField()),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'criptos',
                'managed': False,
            },
        ),
    ]
